# baseurl = "https://wiki.dgraph.io"
baseurl = "http://localhost:1313/latest"
languageCode = "en-us"
theme = "hugo-docs"

# set by build script: title, baseurl
title = "Dgraph Doc"

[params]
  versions = [
    "latest",
    "pre-0.7.3"
]
