# baseurl = "https://wiki.dgraph.io"
baseurl = "http://localhost:8080/0.7"
languageCode = "en-us"
theme = "hugo-docs"

# title is set by the build script using the appropriate version number
title = "Dgraph Doc"

[params]
  versions = [
    "latest",
    "pre-0.7.3"
]
